### ISSUE TITLE
Fresh install fails out of box

### ISSUE THREAD

**Issue by Mitlik** [okken/cards#55]
* cards version: 1.0.0
* Python version: 3.10.0
* Operating System: Microsoft Windows [Version 10.0.17134.1304]

### Description
First time ever install, via pipx.
First commands tried were `cards list` and `cards config` both resulting in FileNotFound exception for the db.
Manually creating `%USERPROFILE%\cards_db` allowed to run, deleting recreates the issue.

### What I Did
```
pipx install cards
refreshenv
cards config
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "%USERPROFILE%\.local\bin\cards.exe\__main__.py", line 7, in <module>
  File "%USERPROFILE%\.local\pipx\venvs\cards\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "%USERPROFILE%\.local\pipx\venvs\cards\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "%USERPROFILE%\.local\pipx\venvs\cards\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "%USERPROFILE%\.local\pipx\venvs\cards\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "%USERPROFILE%\.local\pipx\venvs\cards\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "%USERPROFILE%\.local\pipx\venvs\cards\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "%USERPROFILE%\.local\pipx\venvs\cards\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "%USERPROFILE%\.local\pipx\venvs\cards\lib\site-packages\cards\cli.py", line 102, in config
    with cards_db() as db:
  File "C:\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "%USERPROFILE%\.local\pipx\venvs\cards\lib\site-packages\cards\cli.py", line 134, in cards_db
    db = cards.CardsDB(db_path)
  File "%USERPROFILE%\.local\pipx\venvs\cards\lib\site-packages\cards\api.py", line 50, in __init__
    self._db = DB(db_path, ".cards_db")
  File "%USERPROFILE%\.local\pipx\venvs\cards\lib\site-packages\cards\db.py", line 11, in __init__
    self._db = tinydb.TinyDB(db_path / f"{db_file_prefix}.json")
  File "%USERPROFILE%\.local\pipx\venvs\cards\lib\site-packages\tinydb\database.py", line 89, in __init__
    self._storage = storage(*args, **kwargs)  # type: Storage
  File "%USERPROFILE%\.local\pipx\venvs\cards\lib\site-packages\tinydb\storages.py", line 102, in __init__
    touch(path, create_dirs=create_dirs)
  File "%USERPROFILE%\.local\pipx\venvs\cards\lib\site-packages\tinydb\storages.py", line 31, in touch
    with open(path, 'a'):
FileNotFoundError: [Errno 2] No such file or directory: '%USERPROFILE%\\cards_db\\.cards_db.json'
```

**Comment by okken** [comment]
So sorry about that. I'll take a look asap.
In the meantime, you can try creating a cards_db directory in your user home directory.
That should allow you to use cards.

**Comment by okken** [comment]
Even if that works, leave this issue open, because I want to fix the "out of the box" experience.

**Comment by okken** [comment]
Ok. problem was fixed in GH, just not published to pypi.
I've bumped the version to 1.0.1 and re-published to pypi.
Fresh install should work now.
